version: "3.8"

services:
  backend-jenkins:
    image: node:18-alpine
    container_name: ezyshopper-backend-jenkins
    restart: unless-stopped
    working_dir: /usr/src/app
    command: sh -c "npm install && node server.js"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - UPSTASH_REDIS_URL=${UPSTASH_REDIS_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - CLIENT_URL=${CLIENT_URL}
    ports:
      - "3001:3000"
    depends_on:
      - mongo-jenkins
    networks:
      - ezyshopper-network

  frontend-jenkins:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ezyshopper-frontend-jenkins
    restart: unless-stopped
    ports:
    - "5174:80"   # nginx exposes 80
    depends_on:
    - backend-jenkins
    networks:
    - ezyshopper-network
    working_dir: /app
    volumes:
      - ./frontend:/app

  mongo-jenkins:
    image: mongo:6.0
    container_name: ezyshopper-mongo-jenkins
    restart: unless-stopped
    volumes:
      - mongo_data_jenkins:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ecommerce_db
    ports:
      - "27018:27017"
    networks:
      - ezyshopper-network

volumes:
  mongo_data_jenkins:

networks:
  ezyshopper-network:
    driver: bridge
